name: EcoLeaderboards
main: com.gmail.mrphpfan.EcoLeaderboards
version: 1.0
depend: [PermissionsEx, Vault, Essentials]

commands:
  el:
    description: Re-rank the sign leaderboards.
    usage: /el reload
permissions:
  EcoLeaderboards.*:
    default: op
    description: All EcoLeaderboards permissions.
    children:
      EcoLeaderboards.place: true
      EcoLeaderboards.reload: true
      EcoLeaderboards.position: true
  EcoLeaderboards.place:
    description: Ability to create a baltop leaderboard with a sign
    default: false
  EcoLeaderboards.reload:
    description: Update the current balances on signs
    default: false
  EcoLeaderboards.position:
    description: Gets the user and balance at a certain rank (1 - 10)
    default: false
